---
- name: Playbook to create a user and a client on Red Hat Build of Keycloak
  hosts: all  
  tasks:

    - name: Generate keycloak auth token
      ansible.builtin.uri:
        url: "{{ rhbk_management_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body: "client_id={{ rhbk_auth_client }}&username={{ rhbk_admin_user }}&password={{ rhbk_admin_password }}&grant_type=password"
        validate_certs: false
      no_log: false
      register: rhbk_auth_response
      until: rhbk_auth_response.status == 200
      retries: 5
      delay: 2

    - name: Retrieve realm-management client
      ansible.builtin.uri:
        url: "{{ rhbk_management_url }}/admin/realms/{{ rhbk_realm }}/clients?clientId=realm-management"
        method: GET        
        validate_certs: false
        headers:
          Authorization: "Bearer {{ rhbk_auth_response.json.access_token }}"
        status_code: 
          - 200          
      no_log: false
      register: rhbk_client_response
      until: rhbk_client_response.status == 200    

    - name: Debug client response
      ansible.builtin.debug:
        var: "{{ rhbk_client_response }}"
