---
- name: Playbook for Red Hat Build of Keycloak
  hosts: all  
  tasks:
    - name: Generate keycloak auth token
      ansible.builtin.uri:
        url: "{{ rhbk_management_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body: "client_id={{ rhbk_auth_client }}&username={{ rhbk_admin_user }}&password={{ rhbk_admin_password }}&grant_type=password"
        validate_certs: false
      no_log: false
      register: rhbk_auth_response
      until: rhbk_auth_response.status == 200
      retries: 5
      delay: 2